name: Build ISO
on:
  workflow_run:
    workflows: ["bluebuild"]
    types: [completed]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build ISO
    runs-on: ubuntu-24.04
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    strategy:
      fail-fast: false
      matrix:
        image:
          - shadowos-linux
          - shadowos-linux-nvidia
          - shadowos-linux-steam
          - shadowos-linux-nvidia-steam
    permissions:
      contents: read
      packages: read
      id-token: write
    steps:
      - name: Maximize build space
        uses: jlumbroso/free-disk-space@v1.3.1

      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate ShadowOS ISO
        uses: Zeglius/titanoboa@revamp-pr
        id: titanoboa
        with:
          image-ref: ghcr.io/shadowos-linux/${{ matrix.image }}:latest
          iso-dest: ./${{ matrix.image }}-latest.iso

      - name: Upload ISO to Job Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.image }}-iso
          path: |
            ${{ steps.titanoboa.outputs.iso-dest }}
          retention-days: 3
          compression-level: 9
