name: Build Image
on:
  schedule:
    - cron: "00 23 * * *"
      timezone: "Asia/Beirut"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  generate-matrix:
    name: Generate Recipe Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Find Recipes
        id: set-matrix
        shell: bash
        run: |
          cd recipes
          RECIPES=$(find * -mindepth 1 -name "*.yml" -type f | jq -R . | jq -cs .)
          
          echo "Generated Matrix: $RECIPES"
          echo "matrix=$RECIPES" >> $GITHUB_OUTPUT

  bluebuild:
    name: Build Custom Image
    needs: generate-matrix
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        recipe: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Maximize build space
        uses: jlumbroso/free-disk-space@main
        with: 
         tool-cache: true

      - name: Checkout
        uses: actions/checkout@main

      - name: Build Custom Image (First Attempt)
        id: build_attempt_1
        continue-on-error: true
        uses: blue-build/github-action@main
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          maximize_build_space: true
          build_chunked_oci: false
          chunkah: true

      - name: Build Custom Image (Second Attempt)
        id: build_attempt_2
        if: steps.build_attempt_1.outcome == 'failure'
        continue-on-error: true
        uses: blue-build/github-action@main
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          maximize_build_space: true
          build_chunked_oci: false
          chunkah: true

      - name: Build Custom Image (Third Attempt)
        id: build_attempt_3
        if: steps.build_attempt_2.outcome == 'failure'
        uses: blue-build/github-action@main
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          maximize_build_space: true
          build_chunked_oci: false
          chunkah: true
