name: bluebuild
on:
  schedule:
    - cron:
        "15 21 * * *"

#  push:
#    paths-ignore: # don't rebuild if only documentation has changed
#      - "**.md"
#      - ".github/workflows/**"

  pull_request:
  workflow_dispatch: # allow manually triggering builds

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-base:
    name: Build Base Variants
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - shadowos-linux.yml
          - shadowos-linux-nvidia.yml
    steps:
      - name: Maximize build space
        uses: jlumbroso/free-disk-space@v1.3.1

      - name: Build Base Images
        uses: blue-build/github-action@v1.11
        with:
          recipe: variants/${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          build_chunked_oci: true
          maximize_build_space: true

  build-steam:
    name: Build Steam Variants
    needs: build-base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - shadowos-linux-steam.yml
          - shadowos-linux-nvidia-steam.yml
    steps:
      - name: Maximize build space
        uses: jlumbroso/free-disk-space@v1.3.1

      - name: Build Steam Images
        uses: blue-build/github-action@v1.11
        with:
          recipe: variants/${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          build_chunked_oci: true
          maximize_build_space: true
