name: Build ISO
on:
  workflow_run:
    workflows: ["bluebuild"]
    types: [completed]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build ISO
    runs-on: ubuntu-24.04
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    strategy:
      fail-fast: false
      matrix:
        image:
          - shadowos-linux
          - shadowos-linux-nvidia
          - shadowos-linux-steam
          - shadowos-linux-nvidia-steam
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Maximize build space
        uses: jlumbroso/free-disk-space@v1.3.1

      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Fedora Release
        id: fedora_version
        uses: sgallagher/get-fedora-releases-action@v1

      - name: Clean Fedora Version
        id: clean_version
        shell: bash
        run: |
          VERSION=$(echo "${{ steps.fedora_version.outputs.stable }}" | grep -oE '[0-9]+' | sort -rn | head -n 1)
          echo "stable_one=$VERSION" >> $GITHUB_OUTPUT
          echo "Selected Fedora Version: $VERSION"

      - name: Prepare Local Payload
        run: |
          IMAGE_REF="ghcr.io/shadowos-linux/${{ matrix.image }}:latest"
          sudo podman pull $IMAGE_REF
          sudo podman tag $IMAGE_REF localhost/payload:latest

      - name: Create ISO Config
        run: |
          mkdir -p ./installer
          cat <<EOF > ./installer/iso.yaml
          variant: cosmic-atomic
          version: "${{ steps.clean_version.outputs.stable_one }}"
          EOF
          
      - name: Generate ShadowOS ISO
        uses: Zeglius/titanoboa@revamp-pr
        id: titanoboa
        with:
          image-ref: localhost/payload:latest
          iso-config: ./installer/iso.yaml
          compression: squashfs
          livesys: true
          iso-dest: ./${{ matrix.image }}-latest.iso

      - name: Upload ISO to Job Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.image }}-iso
          path: ./${{ matrix.image }}-latest.iso
          retention-days: 4
          compression-level: 9
